
services:
  fastapi_app:
    build: .
    container_name: traffic_sign_classifier
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1  # Daha hızlı log çıktısı
